spring:
  application:
    name: dsp-model-prediction

model:
  deepfm:
    ctr:
      v1:
        model-path: classpath:model/ctr/v1/criteo_ctr_model.onnx
        preprocessor-path: classpath:model/ctr/v1/criteo_preprocessor.json
        input-node: criteo_features
        output-node: ctr_prob
        batch-size: 100
        optimization-level: 1
      v2:
        model-path: classpath:model/ctr/v2/ctr_deepfm_model.onnx
        preprocessor-path: classpath:model/ctr/v2/ctr_preprocessor.json
        input-node: features
        output-node: click_prob
        batch-size: 100
        optimization-level: 1
